from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from datetime import date, timedelta
from blood_app.models import DonorProfile, BloodRequest


class Command(BaseCommand):
    help = 'Seeds database with realistic Bangladeshi donors from all major districts and diverse backgrounds (Hindu & Muslim).'

    def add_arguments(self, parser):
        parser.add_argument(
            '--no-flush',
            action='store_true',
            help='Skip flushing existing records before seeding',
        )
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Explicitly clear existing data before seeding (default behavior)',
        )

    def handle(self, *args, **options):
        # Default behavior: Flush DB cleanly for a fresh start unless --no-flush is passed
        should_flush = not options.get('no_flush', False)

        if should_flush:
            self.stdout.write('Clearing all existing blood requests, donor profiles, and users...')
            BloodRequest.objects.all().delete()
            DonorProfile.objects.all().delete()
            User.objects.all().delete()
            self.stdout.write('Starting fresh seed with realistic data...')

        # 1. Administrator Setup (Single Admin in DB: Arka Karmoker)
        admin_user, _ = User.objects.get_or_create(
            username='admin',
            defaults={
                'first_name': 'Arka',
                'last_name': 'Karmoker',
                'email': 'admin@example.com',
                'is_staff': True,
                'is_superuser': True,
            }
        )
        admin_user.first_name = 'Arka'
        admin_user.last_name = 'Karmoker'
        admin_user.email = 'admin@example.com'
        admin_user.is_staff = True
        admin_user.is_superuser = True
        admin_user.set_password('1234')
        admin_user.save()

        # 2. Dedicated Reviewer Accounts for Feature & Role Verification (Password: 1234)
        today = date.today()
        reviewer_accounts = [
            {
                'username': 'testdonor',
                'first_name': 'Test',
                'last_name': 'Donor',
                'email': 'test.donor@example.com',
                'password': '1234',
                'blood_group': 'O-',
                'phone': '01711000001',
                'location': 'Dhaka',
                'address': 'House 12, Road 27, Dhanmondi, Dhaka',
                'date_of_birth': date(1998, 1, 15),
                'last_donation_date': today - timedelta(days=100),
                'is_available': True,
                'description': 'Active voluntary universal donor. Test account for checking donor profile editing, eligibility calculation, and instant availability toggle.',
            },
            {
                'username': 'testrequester',
                'first_name': 'Test',
                'last_name': 'Requester',
                'email': 'test.requester@example.com',
                'password': '1234',
                'blood_group': 'A+',
                'phone': '01811000002',
                'location': 'Dhaka',
                'address': 'Section 10, Mirpur, Dhaka',
                'date_of_birth': date(1995, 6, 20),
                'last_donation_date': today - timedelta(days=150),
                'is_available': True,
                'description': 'Patient attendant / blood requester. Test account for managing emergency requests, editing requests, and marking as fulfilled.',
            },
            {
                'username': 'testrequester1',
                'first_name': 'Test',
                'last_name': 'Requester1',
                'email': 'test.requester1@example.com',
                'password': '1234',
                'blood_group': 'B+',
                'phone': '01911000003',
                'location': 'Chittagong',
                'address': 'GEC Circle, Chittagong',
                'date_of_birth': date(1999, 4, 12),
                'last_donation_date': today - timedelta(days=95),
                'is_available': True,
                'description': 'Secondary donor account for security & permission testing (verifies HTTP 403 Forbidden when accessing other users\' edit/delete endpoints).',
            },
        ]

        test_requester_user = None
        for acc in reviewer_accounts:
            user, _ = User.objects.get_or_create(
                username=acc['username'],
                defaults={
                    'first_name': acc['first_name'],
                    'last_name': acc['last_name'],
                    'email': acc['email'],
                }
            )
            user.first_name = acc['first_name']
            user.last_name = acc['last_name']
            user.email = acc['email']
            user.is_staff = False
            user.is_superuser = False
            user.set_password(acc['password'])
            user.save()

            if acc['username'] == 'testrequester':
                test_requester_user = user

            DonorProfile.objects.update_or_create(
                user=user,
                defaults={
                    'phone': acc['phone'],
                    'blood_group': acc['blood_group'],
                    'location': acc['location'],
                    'address': acc['address'],
                    'date_of_birth': acc['date_of_birth'],
                    'last_donation_date': acc['last_donation_date'],
                    'is_available': acc['is_available'],
                    'description': acc['description'],
                }
            )

        # 3. Comprehensive Bangladeshi Donors (Muslim & Hindu, All major districts, All 8 blood groups)
        sample_donors = [
            # ======================== DHAKA DIVISION ========================
            {
                'username': 'tanvir_dhaka',
                'first_name': 'Tanvir',
                'last_name': 'Hossain',
                'email': 'tanvir.hossain@example.com',
                'blood_group': 'B+',
                'phone': '01712340001',
                'location': 'Dhaka',
                'address': 'House 14, Road 7, Dhanmondi, Dhaka',
                'date_of_birth': date(1996, 5, 14),
                'last_donation_date': today - timedelta(days=120),
                'is_available': True,
                'description': 'Software Engineer & voluntary regular donor. Available on weekends in Dhanmondi & Panthapath.',
            },
            {
                'username': 'puja_dhaka',
                'first_name': 'Puja',
                'last_name': 'Karmakar',
                'email': 'puja.karmakar@example.com',
                'blood_group': 'A+',
                'phone': '01812340002',
                'location': 'Dhaka',
                'address': 'Block C, Lalmatia, Dhaka',
                'date_of_birth': date(1998, 8, 22),
                'last_donation_date': today - timedelta(days=105),
                'is_available': True,
                'description': 'University researcher. Ready to donate blood for emergency medical needs.',
            },
            {
                'username': 'anik_dhaka',
                'first_name': 'Anik',
                'last_name': 'Chakraborty',
                'email': 'anik.chakraborty@example.com',
                'blood_group': 'O+',
                'phone': '01912340003',
                'location': 'Dhaka',
                'address': 'Sector 4, Uttara, Dhaka',
                'date_of_birth': date(1995, 3, 10),
                'last_donation_date': today - timedelta(days=140),
                'is_available': True,
                'description': 'Regular voluntary donor. Fast response in Uttara and Kurmitola areas.',
            },
            {
                'username': 'tanjila_dhaka',
                'first_name': 'Tanjila',
                'last_name': 'Akter',
                'email': 'tanjila.a@example.com',
                'blood_group': 'B+',
                'phone': '01612340004',
                'location': 'Dhaka',
                'address': 'Mirpur 10, Dhaka',
                'date_of_birth': date(2000, 11, 5),
                'last_donation_date': None,
                'is_available': True,
                'description': 'College student. Excited and ready for first-time donation in Mirpur area.',
            },
            {
                'username': 'kazi_gazipur',
                'first_name': 'Kazi',
                'last_name': 'Enamul',
                'email': 'kazi.enamul@example.com',
                'blood_group': 'O-',
                'phone': '01712340005',
                'location': 'Gazipur',
                'address': 'Chowrasta, Gazipur Sadar',
                'date_of_birth': date(1993, 1, 18),
                'last_donation_date': today - timedelta(days=180),
                'is_available': True,
                'description': 'Universal donor (O-). Available for urgent blood calls in Gazipur and Tongi.',
            },
            {
                'username': 'moumita_narayanganj',
                'first_name': 'Moumita',
                'last_name': 'Saha',
                'email': 'moumita.saha@example.com',
                'blood_group': 'O-',
                'phone': '01812340006',
                'location': 'Narayanganj',
                'address': 'Chashara, Narayanganj',
                'date_of_birth': date(1997, 7, 12),
                'last_donation_date': today - timedelta(days=160),
                'is_available': True,
                'description': 'Bank officer and active voluntary donor in Narayanganj Sadar.',
            },
            {
                'username': 'farhana_tangail',
                'first_name': 'Farhana',
                'last_name': 'Khanam',
                'email': 'farhana.khanam@example.com',
                'blood_group': 'O+',
                'phone': '01912340007',
                'location': 'Tangail',
                'address': 'Victoria Road, Tangail Sadar',
                'date_of_birth': date(1999, 4, 3),
                'last_donation_date': today - timedelta(days=95),
                'is_available': True,
                'description': 'School teacher. Willing to donate for critical patients in Tangail.',
            },

            # ======================== CHITTAGONG / CHATTOGRAM DIVISION ========================
            {
                'username': 'sakib_ctg',
                'first_name': 'Sakib',
                'last_name': 'Hasan',
                'email': 'sakib.h@example.com',
                'blood_group': 'O-',
                'phone': '01755667788',
                'location': 'Chittagong',
                'address': 'Agrabad Commercial Area, Chattogram',
                'date_of_birth': date(1994, 9, 25),
                'last_donation_date': today - timedelta(days=150),
                'is_available': True,
                'description': 'Universal donor (O-). Dedicated to emergency calls at CMCH.',
            },
            {
                'username': 'subrata_ctg',
                'first_name': 'Subrata',
                'last_name': 'Das',
                'email': 'subrata.das@example.com',
                'blood_group': 'A+',
                'phone': '01812340008',
                'location': 'Chittagong',
                'address': 'Nasirabad, Chattogram',
                'date_of_birth': date(1992, 12, 1),
                'last_donation_date': today - timedelta(days=40),
                'is_available': False,
                'description': 'Recently donated blood on recovery cooldown until next month.',
            },
            {
                'username': 'nusrat_ctg',
                'first_name': 'Nusrat',
                'last_name': 'Jahan',
                'email': 'nusrat.jahan@example.com',
                'blood_group': 'O+',
                'phone': '01912340009',
                'location': 'Chittagong',
                'address': 'GEC Circle, Chattogram',
                'date_of_birth': date(2001, 2, 14),
                'last_donation_date': today - timedelta(days=110),
                'is_available': True,
                'description': 'Medical student. Ready to donate blood anytime around Panchlaish and GEC.',
            },
            {
                'username': 'priyanka_ctg',
                'first_name': 'Priyanka',
                'last_name': 'Dey',
                'email': 'priyanka.dey@example.com',
                'blood_group': 'B+',
                'phone': '01612340010',
                'location': 'Chittagong',
                'address': 'Jamalkhan Road, Chattogram',
                'date_of_birth': date(1998, 6, 29),
                'last_donation_date': today - timedelta(days=130),
                'is_available': True,
                'description': 'Regular blood donor and social volunteer in Jamalkhan area.',
            },
            {
                'username': 'rasheda_cox',
                'first_name': 'Rasheda',
                'last_name': 'Parveen',
                'email': 'rasheda.parveen@example.com',
                'blood_group': 'B-',
                'phone': '01712340011',
                'location': 'Cox\'s Bazar',
                'address': 'Kolatoli Road, Cox\'s Bazar',
                'date_of_birth': date(1996, 10, 19),
                'last_donation_date': today - timedelta(days=145),
                'is_available': True,
                'description': 'Rare B- donor based in Cox\'s Bazar Sadar.',
            },
            {
                'username': 'barnali_cox',
                'first_name': 'Barnali',
                'last_name': 'Sen',
                'email': 'barnali.sen@example.com',
                'blood_group': 'O+',
                'phone': '01812340012',
                'location': 'Cox\'s Bazar',
                'address': 'Main Road, Cox\'s Bazar Sadar',
                'date_of_birth': date(1999, 1, 8),
                'last_donation_date': today - timedelta(days=100),
                'is_available': True,
                'description': 'Hospitality professional. Available for local hospital emergencies.',
            },
            {
                'username': 'rahim_feni',
                'first_name': 'Rahim',
                'last_name': 'Ahmed',
                'email': 'rahim.ahmed@example.com',
                'blood_group': 'O+',
                'phone': '01711223344',
                'location': 'Feni',
                'address': 'Trunk Road, Feni Sadar',
                'date_of_birth': date(1993, 8, 15),
                'last_donation_date': today - timedelta(days=110),
                'is_available': True,
                'description': 'Regular voluntary donor. Happy to help anytime in Feni and nearby areas.',
            },
            {
                'username': 'karim_feni',
                'first_name': 'Karim',
                'last_name': 'Uddin',
                'email': 'karim.u@example.com',
                'blood_group': 'A+',
                'phone': '01812345678',
                'location': 'Feni',
                'address': 'SSK Road, Feni',
                'date_of_birth': date(1991, 5, 20),
                'last_donation_date': today - timedelta(days=45),
                'is_available': False,
                'description': 'Recently donated blood for a surgery patient.',
            },
            {
                'username': 'fatima_feni',
                'first_name': 'Fatima',
                'last_name': 'Begum',
                'email': 'fatima.b@example.com',
                'blood_group': 'A-',
                'phone': '01822334455',
                'location': 'Feni',
                'address': 'Hospital Road, Feni',
                'date_of_birth': date(1995, 12, 10),
                'last_donation_date': today - timedelta(days=100),
                'is_available': True,
                'description': 'A- rare blood donor in Feni district.',
            },
            {
                'username': 'pranto_feni',
                'first_name': 'Pranto',
                'last_name': 'Debnath',
                'email': 'pranto.debnath@example.com',
                'blood_group': 'A-',
                'phone': '01912340013',
                'location': 'Feni',
                'address': 'Ramsundar Road, Feni',
                'date_of_birth': date(1997, 3, 21),
                'last_donation_date': today - timedelta(days=125),
                'is_available': True,
                'description': 'Rare blood group volunteer donor in Feni.',
            },
            {
                'username': 'sourav_comilla',
                'first_name': 'Sourav',
                'last_name': 'Bhowmik',
                'email': 'sourav.bhowmik@example.com',
                'blood_group': 'O-',
                'phone': '01612340014',
                'location': 'Comilla',
                'address': 'Kandirpar, Cumilla',
                'date_of_birth': date(1994, 7, 30),
                'last_donation_date': today - timedelta(days=165),
                'is_available': True,
                'description': 'Universal donor (O-). Available for emergency surgeries in Cumilla.',
            },
            {
                'username': 'ashfaqur_comilla',
                'first_name': 'Ashfaqur',
                'last_name': 'Rahman',
                'email': 'ashfaqur.rahman@example.com',
                'blood_group': 'O+',
                'phone': '01712340015',
                'location': 'Comilla',
                'address': 'Tomchom Bridge, Cumilla',
                'date_of_birth': date(1996, 11, 27),
                'last_donation_date': today - timedelta(days=115),
                'is_available': True,
                'description': 'Youth blood donation club member in Cumilla.',
            },
            {
                'username': 'ananya_comilla',
                'first_name': 'Ananya',
                'last_name': 'Bhowmick',
                'email': 'ananya.bhowmick@example.com',
                'blood_group': 'B+',
                'phone': '01812340016',
                'location': 'Comilla',
                'address': 'Police Line Road, Cumilla',
                'date_of_birth': date(2000, 9, 15),
                'last_donation_date': today - timedelta(days=95),
                'is_available': True,
                'description': 'College lecturer. Dedicated voluntary donor in Cumilla city.',
            },
            {
                'username': 'jahidul_noakhali',
                'first_name': 'Jahidul',
                'last_name': 'Islam',
                'email': 'jahidul.islam@example.com',
                'blood_group': 'A-',
                'phone': '01912340017',
                'location': 'Noakhali',
                'address': 'Maijdee Court, Noakhali',
                'date_of_birth': date(1995, 4, 18),
                'last_donation_date': today - timedelta(days=130),
                'is_available': True,
                'description': 'Always ready for A- emergency requirements at Noakhali Sadar Hospital.',
            },
            {
                'username': 'tahmina_brahmanbaria',
                'first_name': 'Tahmina',
                'last_name': 'Sultana',
                'email': 'tahmina.sultana@example.com',
                'blood_group': 'A+',
                'phone': '01612340018',
                'location': 'Brahmanbaria',
                'address': 'Kawtoli, Brahmanbaria Sadar',
                'date_of_birth': date(1998, 2, 8),
                'last_donation_date': today - timedelta(days=105),
                'is_available': True,
                'description': 'Active social worker and regular blood donor in Brahmanbaria.',
            },

            # ======================== SYLHET DIVISION ========================
            {
                'username': 'sumon_sylhet',
                'first_name': 'Sumon',
                'last_name': 'Paul',
                'email': 'sumon.p@example.com',
                'blood_group': 'AB+',
                'phone': '01611223399',
                'location': 'Sylhet',
                'address': 'Zindabazar, Sylhet Sadar',
                'date_of_birth': date(1995, 6, 17),
                'last_donation_date': None,
                'is_available': True,
                'description': 'Ready for first-time donation. Can reach Osmani Medical quickly.',
            },
            {
                'username': 'arifur_sylhet',
                'first_name': 'Arifur',
                'last_name': 'Rahman',
                'email': 'arifur.rahman@example.com',
                'blood_group': 'A-',
                'phone': '01712340019',
                'location': 'Sylhet',
                'address': 'Amberkhana, Sylhet',
                'date_of_birth': date(1993, 10, 4),
                'last_donation_date': today - timedelta(days=140),
                'is_available': True,
                'description': 'Frequent donor for critical leukemia patients at Osmani Medical.',
            },
            {
                'username': 'sadia_sylhet',
                'first_name': 'Sadia',
                'last_name': 'Afrin',
                'email': 'sadia.afrin@example.com',
                'blood_group': 'AB+',
                'phone': '01812340020',
                'location': 'Sylhet',
                'address': 'Shahjalal Upashahar, Sylhet',
                'date_of_birth': date(1999, 12, 23),
                'last_donation_date': today - timedelta(days=115),
                'is_available': True,
                'description': 'Registered medical technologist and blood donor.',
            },
            {
                'username': 'shreya_sylhet',
                'first_name': 'Shreya',
                'last_name': 'Das',
                'email': 'shreya.das@example.com',
                'blood_group': 'O+',
                'phone': '01912340021',
                'location': 'Sylhet',
                'address': 'Subidbazar, Sylhet',
                'date_of_birth': date(2001, 8, 11),
                'last_donation_date': today - timedelta(days=100),
                'is_available': True,
                'description': 'University student and voluntary donor in Sylhet.',
            },

            # ======================== RAJSHAHI DIVISION ========================
            {
                'username': 'mahfuzul_rajshahi',
                'first_name': 'Mahfuzul',
                'last_name': 'Haque',
                'email': 'mahfuzul.haque@example.com',
                'blood_group': 'AB+',
                'phone': '01712340022',
                'location': 'Rajshahi',
                'address': 'Shaheb Bazar, Rajshahi',
                'date_of_birth': date(1994, 3, 29),
                'last_donation_date': today - timedelta(days=130),
                'is_available': True,
                'description': 'Regular blood donor near RMCH. Available day and night.',
            },
            {
                'username': 'jannatul_rajshahi',
                'first_name': 'Jannatul',
                'last_name': 'Ferdous',
                'email': 'jannatul.ferdous@example.com',
                'blood_group': 'O-',
                'phone': '01812340023',
                'location': 'Rajshahi',
                'address': 'Kazihata, Rajshahi',
                'date_of_birth': date(1997, 5, 16),
                'last_donation_date': today - timedelta(days=155),
                'is_available': True,
                'description': 'Universal donor (O-) ready to support emergency cases in Rajshahi.',
            },
            {
                'username': 'shubhro_rajshahi',
                'first_name': 'Shubhro',
                'last_name': 'Roy',
                'email': 'shubhro.roy@example.com',
                'blood_group': 'AB+',
                'phone': '01912340024',
                'location': 'Rajshahi',
                'address': 'Motihar, Rajshahi',
                'date_of_birth': date(1996, 9, 2),
                'last_donation_date': today - timedelta(days=35),
                'is_available': False,
                'description': 'Recently donated blood for an emergency surgery at RMCH.',
            },
            {
                'username': 'nazmul_bogura',
                'first_name': 'Nazmul',
                'last_name': 'Huda',
                'email': 'nazmul.huda@example.com',
                'blood_group': 'B+',
                'phone': '01612340025',
                'location': 'Bogura',
                'address': 'Satmatha, Bogura Sadar',
                'date_of_birth': date(1992, 11, 14),
                'last_donation_date': today - timedelta(days=110),
                'is_available': True,
                'description': 'Active volunteer near Shaheed Ziaur Rahman Medical College.',
            },
            {
                'username': 'palash_bogura',
                'first_name': 'Palash',
                'last_name': 'Barman',
                'email': 'palash.barman@example.com',
                'blood_group': 'O+',
                'phone': '01712340026',
                'location': 'Bogura',
                'address': 'Thonthonia, Bogura',
                'date_of_birth': date(1995, 1, 28),
                'last_donation_date': today - timedelta(days=125),
                'is_available': True,
                'description': 'Always ready to donate O+ blood for patients in Bogura.',
            },
            {
                'username': 'sabina_pabna',
                'first_name': 'Sabina',
                'last_name': 'Yasmin',
                'email': 'sabina.yasmin@example.com',
                'blood_group': 'B+',
                'phone': '01812340027',
                'location': 'Pabna',
                'address': 'Abdul Hamid Road, Pabna Sadar',
                'date_of_birth': date(1998, 7, 7),
                'last_donation_date': today - timedelta(days=105),
                'is_available': True,
                'description': 'Voluntary donor assisting patients at Pabna General Hospital.',
            },

            # ======================== KHULNA DIVISION ========================
            {
                'username': 'farhan_khulna',
                'first_name': 'Farhan',
                'last_name': 'Sadik',
                'email': 'farhan.sadik@example.com',
                'blood_group': 'O+',
                'phone': '01912340028',
                'location': 'Khulna',
                'address': 'Shibbari Mor, Khulna',
                'date_of_birth': date(1995, 8, 19),
                'last_donation_date': today - timedelta(days=120),
                'is_available': True,
                'description': 'Donated blood 7 times. Ready for emergencies in Khulna city.',
            },
            {
                'username': 'dipankar_khulna',
                'first_name': 'Dipankar',
                'last_name': 'Saha',
                'email': 'dipankar.saha@example.com',
                'blood_group': 'AB-',
                'phone': '01612340029',
                'location': 'Khulna',
                'address': 'Sonadanga, Khulna',
                'date_of_birth': date(1993, 4, 12),
                'last_donation_date': today - timedelta(days=170),
                'is_available': True,
                'description': 'Rare AB- donor. Reach out for urgent surgical or accident cases.',
            },
            {
                'username': 'sumaiya_khulna',
                'first_name': 'Sumaiya',
                'last_name': 'Islam',
                'email': 'sumaiya.islam@example.com',
                'blood_group': 'A+',
                'phone': '01712340030',
                'location': 'Khulna',
                'address': 'Boyra, Khulna',
                'date_of_birth': date(2000, 3, 25),
                'last_donation_date': today - timedelta(days=95),
                'is_available': True,
                'description': 'Nursing student at Khulna Medical. Active voluntary donor.',
            },
            {
                'username': 'trisha_khulna',
                'first_name': 'Trisha',
                'last_name': 'Ghosh',
                'email': 'trisha.ghosh@example.com',
                'blood_group': 'AB+',
                'phone': '01812340031',
                'location': 'Khulna',
                'address': 'Daulatpur, Khulna',
                'date_of_birth': date(1997, 10, 31),
                'last_donation_date': today - timedelta(days=110),
                'is_available': True,
                'description': 'Dedicated blood donor in northern Khulna.',
            },
            {
                'username': 'tariqul_jessore',
                'first_name': 'Tariqul',
                'last_name': 'Islam',
                'email': 'tariqul.islam@example.com',
                'blood_group': 'A+',
                'phone': '01912340032',
                'location': 'Jessore',
                'address': 'Chowrasta, Jashore Sadar',
                'date_of_birth': date(1994, 6, 9),
                'last_donation_date': today - timedelta(days=130),
                'is_available': True,
                'description': 'Quick responder for Jashore General Hospital requirements.',
            },
            {
                'username': 'niloy_jessore',
                'first_name': 'Niloy',
                'last_name': 'Ghosh',
                'email': 'niloy.ghosh@example.com',
                'blood_group': 'O+',
                'phone': '01612340033',
                'location': 'Jessore',
                'address': 'Jail Road, Jashore',
                'date_of_birth': date(1996, 2, 17),
                'last_donation_date': today - timedelta(days=115),
                'is_available': True,
                'description': 'Volunteer at red crescent blood program in Jashore.',
            },
            {
                'username': 'golam_kushtia',
                'first_name': 'Golam',
                'last_name': 'Mostafa',
                'email': 'golam.mostafa@example.com',
                'blood_group': 'O+',
                'phone': '01712340034',
                'location': 'Kushtia',
                'address': 'NS Road, Kushtia Sadar',
                'date_of_birth': date(1992, 8, 4),
                'last_donation_date': today - timedelta(days=125),
                'is_available': True,
                'description': 'Regular donor in Kushtia district. Happy to assist patients.',
            },
            {
                'username': 'bikash_kushtia',
                'first_name': 'Bikash',
                'last_name': 'Chandra Roy',
                'email': 'bikash.roy@example.com',
                'blood_group': 'O+',
                'phone': '01812340035',
                'location': 'Kushtia',
                'address': 'Majampur, Kushtia',
                'date_of_birth': date(1995, 12, 19),
                'last_donation_date': today - timedelta(days=100),
                'is_available': True,
                'description': 'Voluntary blood donor in Kushtia town.',
            },

            # ======================== BARISHAL DIVISION ========================
            {
                'username': 'saiful_barishal',
                'first_name': 'Saiful',
                'last_name': 'Islam',
                'email': 'saiful.islam@example.com',
                'blood_group': 'B-',
                'phone': '01912340036',
                'location': 'Barishal',
                'address': 'C&B Road, Barishal Sadar',
                'date_of_birth': date(1993, 7, 24),
                'last_donation_date': today - timedelta(days=145),
                'is_available': True,
                'description': 'Rare B- donor based in Barishal. Quick to reach SBMCH.',
            },
            {
                'username': 'amitava_barishal',
                'first_name': 'Amitava',
                'last_name': 'Majumder',
                'email': 'amitava.majumder@example.com',
                'blood_group': 'A+',
                'phone': '01612340037',
                'location': 'Barishal',
                'address': 'Natun Bazar, Barishal',
                'date_of_birth': date(1996, 5, 8),
                'last_donation_date': today - timedelta(days=110),
                'is_available': True,
                'description': 'Frequent donor and volunteer in Barishal city.',
            },

            # ======================== RANGPUR DIVISION ========================
            {
                'username': 'mehedi_rangpur',
                'first_name': 'Mehedi',
                'last_name': 'Hasan',
                'email': 'mehedi.hasan@example.com',
                'blood_group': 'A+',
                'phone': '01712340038',
                'location': 'Rangpur',
                'address': 'Dhap, Medical Mor, Rangpur',
                'date_of_birth': date(1995, 9, 13),
                'last_donation_date': today - timedelta(days=120),
                'is_available': True,
                'description': 'Pharmacy graduate. Available for emergency calls at Rangpur Medical.',
            },
            {
                'username': 'joy_rangpur',
                'first_name': 'Joy',
                'last_name': 'Sen',
                'email': 'joy.sen@example.com',
                'blood_group': 'B+',
                'phone': '01812340039',
                'location': 'Rangpur',
                'address': 'Jahaj Company Mor, Rangpur',
                'date_of_birth': date(1998, 1, 26),
                'last_donation_date': today - timedelta(days=105),
                'is_available': True,
                'description': 'Active donor ready for hospital emergencies in Rangpur.',
            },
            {
                'username': 'biplob_dinajpur',
                'first_name': 'Biplob',
                'last_name': 'Roy',
                'email': 'biplob.roy@example.com',
                'blood_group': 'B+',
                'phone': '01912340040',
                'location': 'Dinajpur',
                'address': 'Nimtola, Dinajpur Sadar',
                'date_of_birth': date(1994, 11, 3),
                'last_donation_date': today - timedelta(days=135),
                'is_available': True,
                'description': 'Regular blood donor in Dinajpur district.',
            },
            {
                'username': 'rupa_dinajpur',
                'first_name': 'Rupa',
                'last_name': 'Rani Roy',
                'email': 'rupa.roy@example.com',
                'blood_group': 'A-',
                'phone': '01612340041',
                'location': 'Dinajpur',
                'address': 'Balubari, Dinajpur',
                'date_of_birth': date(1999, 4, 15),
                'last_donation_date': today - timedelta(days=115),
                'is_available': True,
                'description': 'A- rare blood donor volunteering in Dinajpur.',
            },
            {
                'username': 'alamin_dinajpur',
                'first_name': 'Al-Amin',
                'last_name': 'Sheikh',
                'email': 'alamin.sheikh@example.com',
                'blood_group': 'AB+',
                'phone': '01712340042',
                'location': 'Dinajpur',
                'address': 'Station Road, Dinajpur',
                'date_of_birth': date(1993, 10, 20),
                'last_donation_date': today - timedelta(days=50),
                'is_available': False,
                'description': 'Cooldown period after recent donation at Abdur Rahim Medical.',
            },

            # ======================== MYMENSINGH DIVISION ========================
            {
                'username': 'shahriar_mymensingh',
                'first_name': 'Shahriar',
                'last_name': 'Kabir',
                'email': 'shahriar.kabir@example.com',
                'blood_group': 'AB-',
                'phone': '01812340043',
                'location': 'Mymensingh',
                'address': 'Charpara, Mymensingh Sadar',
                'date_of_birth': date(1994, 8, 14),
                'last_donation_date': today - timedelta(days=150),
                'is_available': True,
                'description': 'Rare AB- donor located 5 minutes from Mymensingh Medical College (MMCH).',
            },
            {
                'username': 'tapas_mymensingh',
                'first_name': 'Tapas',
                'last_name': 'Kumar Das',
                'email': 'tapas.das@example.com',
                'blood_group': 'B-',
                'phone': '01912340044',
                'location': 'Mymensingh',
                'address': 'Ganginar Par, Mymensingh',
                'date_of_birth': date(1996, 12, 5),
                'last_donation_date': today - timedelta(days=140),
                'is_available': True,
                'description': 'B- voluntary donor in Mymensingh. Fast responder.',
            },
        ]

        created_users = []
        for donor_data in sample_donors:
            username = donor_data['username']
            user, _ = User.objects.get_or_create(
                username=username,
                defaults={
                    'first_name': donor_data['first_name'],
                    'last_name': donor_data['last_name'],
                    'email': donor_data['email'],
                }
            )
            user.first_name = donor_data['first_name']
            user.last_name = donor_data['last_name']
            user.email = donor_data['email']
            user.set_password('donor12345')
            user.save()

            created_users.append(user)

            DonorProfile.objects.update_or_create(
                user=user,
                defaults={
                    'phone': donor_data['phone'],
                    'blood_group': donor_data['blood_group'],
                    'location': donor_data['location'],
                    'address': donor_data['address'],
                    'date_of_birth': donor_data.get('date_of_birth'),
                    'last_donation_date': donor_data['last_donation_date'],
                    'is_available': donor_data['is_available'],
                    'description': donor_data['description'],
                }
            )

        # 4. Realistic Bangladeshi Emergency Blood Requests
        sample_requests = [
            # Dedicated test requests for 'testrequester' (Reviewer testing)
            {
                'requester_user': test_requester_user,
                'patient_name': 'Sumaiya Rahman',
                'blood_group': 'O-',
                'hospital_name': 'Dhaka Medical College Hospital (DMCH)',
                'location': 'Dhaka',
                'hospital_address': 'Secretariat Road, DMCH Ward 12, Dhaka',
                'required_date': today + timedelta(days=1),
                'bags_required': 2,
                'contact_number': '01811000002',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Emergency cardiac surgery requiring rare O- negative blood. Active test request for reviewing Edit/Delete, Status update, and Donor Matching.',
            },
            {
                'requester_user': test_requester_user,
                'patient_name': 'Kawsar Ahmed',
                'blood_group': 'A+',
                'hospital_name': 'Square Hospital, Dhaka',
                'location': 'Dhaka',
                'hospital_address': 'Panthapath, Dhaka',
                'required_date': today - timedelta(days=4),
                'bags_required': 1,
                'contact_number': '01811000002',
                'urgency': 'Normal',
                'status': 'Fulfilled',
                'reason': 'Elective knee surgery transfusion successfully completed and marked as fulfilled by requester.',
            },
            {
                'requester_user': created_users[13],  # Rahim (Feni)
                'patient_name': 'Mohammad Rafiq',
                'blood_group': 'O+',
                'hospital_name': 'Feni Modern Sadar Hospital',
                'location': 'Feni',
                'hospital_address': 'Hospital Road, Feni Sadar',
                'required_date': today + timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01711223344',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Patient undergoing emergency orthopedic surgery following a road accident. Immediate whole blood transfusion required.',
            },
            {
                'requester_user': created_users[0],  # Tanvir (Dhaka)
                'patient_name': 'Nusrat Jahan',
                'blood_group': 'A+',
                'hospital_name': 'Square Hospital',
                'location': 'Dhaka',
                'hospital_address': 'Panthapath, Dhaka',
                'required_date': today + timedelta(days=1),
                'bags_required': 3,
                'contact_number': '01812345678',
                'urgency': 'Urgent',
                'status': 'Pending',
                'reason': 'Dengue complications with dropping platelet count. A+ donors requested for direct cross-matching.',
            },
            {
                'requester_user': created_users[7],  # Sakib (Chittagong)
                'patient_name': 'Rehana Parveen',
                'blood_group': 'O-',
                'hospital_name': 'Z.H. Sikder Women\'s Medical College',
                'location': 'Dhaka',
                'hospital_address': 'Rayerbazar, Dhaka',
                'required_date': today + timedelta(days=3),
                'bags_required': 2,
                'contact_number': '01755667788',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Rare negative blood group required for emergency cesarean delivery.',
            },
            {
                'requester_user': created_users[1],  # Puja (Dhaka)
                'patient_name': 'Biplob Kumar Saha',
                'blood_group': 'AB+',
                'hospital_name': 'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
                'location': 'Dhaka',
                'hospital_address': 'Shahbag, Dhaka',
                'required_date': today + timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01911223388',
                'urgency': 'Urgent',
                'status': 'Pending',
                'reason': 'Scheduled cardiac open-heart surgery. Whole blood bags needed in reservation.',
            },
            {
                'requester_user': created_users[21],  # Sumon (Sylhet)
                'patient_name': 'Subrata Mukherjee',
                'blood_group': 'B+',
                'hospital_name': 'Sylhet MAG Osmani Medical College Hospital',
                'location': 'Sylhet',
                'hospital_address': 'Kajolshah, Sylhet',
                'required_date': today + timedelta(days=1),
                'bags_required': 2,
                'contact_number': '01788990011',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Severe gastrointestinal bleeding. Immediate transfusion of B+ whole blood needed.',
            },
            {
                'requester_user': created_users[2],  # Anik (Dhaka)
                'patient_name': 'Farhana Akter',
                'blood_group': 'A-',
                'hospital_name': 'Dhaka Medical College Hospital (DMCH)',
                'location': 'Dhaka',
                'hospital_address': 'Bakshibazar, Old Dhaka',
                'required_date': today + timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01633445566',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Rare A- blood urgently needed for an anemic dialysis patient in Ward 12.',
            },
            {
                'requester_user': created_users[33],  # Mehedi (Rangpur)
                'patient_name': 'Rupa Rani Das',
                'blood_group': 'O+',
                'hospital_name': 'Rangpur Medical College Hospital',
                'location': 'Rangpur',
                'hospital_address': 'Medical Road, Rangpur',
                'required_date': today + timedelta(days=3),
                'bags_required': 3,
                'contact_number': '01522334455',
                'urgency': 'Urgent',
                'status': 'Pending',
                'reason': 'Major hysterectomy procedure requiring fresh O+ blood.',
            },
            {
                'requester_user': created_users[25],  # Mahfuzul (Rajshahi)
                'patient_name': 'Shahinur Islam',
                'blood_group': 'B-',
                'hospital_name': 'Rajshahi Medical College Hospital (RMCH)',
                'location': 'Rajshahi',
                'hospital_address': 'Medical Road, Rajshahi',
                'required_date': today + timedelta(days=1),
                'bags_required': 1,
                'contact_number': '01744556677',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Trauma surgery after highway collision. Rare B- negative blood required immediately.',
            },
            {
                'requester_user': created_users[28],  # Farhan (Khulna)
                'patient_name': 'Joyanta Roy',
                'blood_group': 'A+',
                'hospital_name': 'Khulna Medical College Hospital',
                'location': 'Khulna',
                'hospital_address': 'Boyra, Khulna',
                'required_date': today + timedelta(days=4),
                'bags_required': 2,
                'contact_number': '01855667788',
                'urgency': 'Normal',
                'status': 'Pending',
                'reason': 'Planned knee replacement surgery next week.',
            },
            {
                'requester_user': created_users[17],  # Sourav (Comilla)
                'patient_name': 'Rokeya Begum',
                'blood_group': 'O+',
                'hospital_name': 'Comilla Medical College Hospital',
                'location': 'Comilla',
                'hospital_address': 'Kuchaitoli, Cumilla',
                'required_date': today + timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01966778899',
                'urgency': 'Urgent',
                'status': 'Pending',
                'reason': 'Post-operative transfusion following gallbladder surgery.',
            },
            {
                'requester_user': created_users[31],  # Saiful (Barishal)
                'patient_name': 'Dipak Karmakar',
                'blood_group': 'AB-',
                'hospital_name': 'Sher-e-Bangla Medical College Hospital (SBMCH)',
                'location': 'Barishal',
                'hospital_address': 'Band Road, Barishal',
                'required_date': today + timedelta(days=1),
                'bags_required': 2,
                'contact_number': '01777889900',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Burn unit critical patient needing plasma & AB- blood crossmatch.',
            },
            {
                'requester_user': created_users[27],  # Nazmul (Bogura)
                'patient_name': 'Ashikur Rahman',
                'blood_group': 'O-',
                'hospital_name': 'Shaheed Ziaur Rahman Medical College Hospital',
                'location': 'Bogura',
                'hospital_address': 'Thonthonia, Bogura',
                'required_date': today + timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01688990011',
                'urgency': 'Critical',
                'status': 'Pending',
                'reason': 'Emergency pediatric surgery needing rare O- donor urgently.',
            },
            {
                'requester_user': created_users[35],  # Biplob (Dinajpur)
                'patient_name': 'Priyanka Barman',
                'blood_group': 'B+',
                'hospital_name': 'M Abdur Rahim Medical College Hospital',
                'location': 'Dinajpur',
                'hospital_address': 'Suptipara, Dinajpur',
                'required_date': today + timedelta(days=3),
                'bags_required': 2,
                'contact_number': '01899001122',
                'urgency': 'Urgent',
                'status': 'Pending',
                'reason': 'Severe anemia in pregnancy. Regular B+ donor needed for elective transfusion.',
            },
            {
                'requester_user': created_users[8],  # Subrata (Chittagong)
                'patient_name': 'Tanvir Alam',
                'blood_group': 'B+',
                'hospital_name': 'Chittagong Medical College Hospital',
                'location': 'Chittagong',
                'hospital_address': 'KB Fazlul Kader Road, CMCH Ward 4',
                'required_date': today - timedelta(days=5),
                'bags_required': 1,
                'contact_number': '01998765432',
                'urgency': 'Normal',
                'status': 'Fulfilled',
                'reason': 'Regular thalassemic blood transfusion successfully fulfilled by volunteer donor.',
            },
            {
                'requester_user': created_users[4],  # Kazi Enamul (Gazipur)
                'patient_name': 'Shampa Deb',
                'blood_group': 'O+',
                'hospital_name': 'Shaheed Tajuddin Ahmad Medical College Hospital',
                'location': 'Gazipur',
                'hospital_address': 'Gazipur Sadar',
                'required_date': today - timedelta(days=2),
                'bags_required': 2,
                'contact_number': '01712349988',
                'urgency': 'Urgent',
                'status': 'Fulfilled',
                'reason': 'Emergency delivery transfusion completed safely.',
            },
        ]

        for req_data in sample_requests:
            requester = req_data.pop('requester_user')
            BloodRequest.objects.update_or_create(
                requester=requester,
                patient_name=req_data['patient_name'],
                defaults=req_data,
            )

        total_donors = DonorProfile.objects.count()
        total_requests = BloodRequest.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'Successfully seeded {total_donors} realistic donors and {total_requests} blood requests across Bangladesh!'
        ))
